import type { Comment } from "@/components/comment-data";

export const initialComments: Comment[] = [
  {
    id: "1",
    name: "Leon Go",
    avatar: "/placeholder.svg?height=44&width=44",
    text: "that wasn't Jim Carrey, it was an impersonator named Heather Shaw",
    likes: 34700,
    liked: false,
    timestamp: "11h",
    subscription: "max",
    badges: ["mystic", "critic", "early"],
    replies: [
      {
        id: "1-1",
        name: "Alex V111",
        avatar: "/placeholder.svg?height=32&width=32",
        text: "She already said it wasn't her. She is in a different country atm",
        likes: 1388,
        liked: false,
        timestamp: "11h",
        replyingTo: "Leon Go",
        subscription: "pro",
      },
      {
        id: "1-2",
        name: "King Reaper",
        avatar: "/placeholder.svg?height=32&width=32",
        text: "Country calls Springfield Massachusetts lol she had a show here at the mgm last night lol",
        likes: 41,
        liked: false,
        timestamp: "4h",
        replyingTo: "Alex V111",
      },
      {
        id: "1-3",
        name: "Sebass ID",
        avatar: "/placeholder.svg?height=32&width=32",
        text: "@BrokeBoiJaden",
        likes: 1,
        liked: false,
        timestamp: "48m",
        replyingTo: "King Reaper",
      },
    ],
  },
  {
    id: "2",
    name: "Original Creator",
    avatar: "/placeholder.svg?height=44&width=44",
    text: "Thank you all so much!! couldn't have made this without your support",
    likes: 11340,
    liked: false,
    timestamp: "3d",
    replies: [
      {
        id: "2-1",
        name: "Fan Account XO",
        avatar: "/placeholder.svg?height=32&width=32",
        text: "you deserve every single one of those views!!",
        likes: 540,
        liked: false,
        timestamp: "2d",
        replyingTo: "Original Creator",
      },
      {
        id: "2-2",
        name: "Vibes Only",
        avatar: "/placeholder.svg?height=32&width=32",
        text: "literally the most wholesome creator on here",
        likes: 213,
        liked: false,
        timestamp: "1d",
        replyingTo: "Original Creator",
      },
    ],
  },
  {
    id: "3",
    name: "Vibes Only",
    avatar: "/placeholder.svg?height=44&width=44",
    text: "POV: you found this at 3am and now your fyp is ruined forever",
    likes: 9203,
    liked: true,
    timestamp: "1d",
    pinned: true,
    replies: [],
    image: "https://picsum.photos/400/300?random=1",
    subscription: "pro",
    badges: ["yapper", "veteran"],
  },
  {
    id: "4",
    name: "Techie Watcher",
    avatar: "/placeholder.svg?height=44&width=44",
    text: "The editing on this is next level fr. What app did you use?",
    likes: 2156,
    liked: false,
    timestamp: "22h",
    replies: [
      {
        id: "4-1",
        name: "Original Creator",
        avatar: "/placeholder.svg?height=32&width=32",
        text: "CapCut + a bit of After Effects for the transitions!",
        likes: 1890,
        liked: false,
        timestamp: "20h",
        replyingTo: "Techie Watcher",
        image: "https://picsum.photos/300/200?random=2",
      },
      {
        id: "4-2",
        name: "Techie Watcher",
        avatar: "/placeholder.svg?height=32&width=32",
        text: "thank you!! going to try that right now",
        likes: 87,
        liked: false,
        timestamp: "19h",
        replyingTo: "Original Creator",
      },
      {
        id: "4-3",
        name: "Edit Pro",
        avatar: "/placeholder.svg?height=32&width=32",
        text: "CapCut has that built-in transition pack too if you want even more options",
        likes: 34,
        liked: false,
        timestamp: "15h",
        replyingTo: "Original Creator",
      },
    ],
  },
  {
    id: "5",
    name: "Just Passing By",
    avatar: "/placeholder.svg?height=44&width=44",
    text: "imagine being this talented. i can barely make toast",
    likes: 6741,
    liked: false,
    timestamp: "20h",
    replies: [],
    sticker: "https://picsum.photos/80/80?random=10",
  },
  {
    id: "6",
    name: "Aesthetic Arc",
    avatar: "/placeholder.svg?height=44&width=44",
    text: "not me commenting just to boost the engagement (also this is incredible)",
    likes: 3308,
    liked: false,
    timestamp: "15h",
    replies: [
      {
        id: "6-1",
        name: "Midnight Scroller",
        avatar: "/placeholder.svg?height=32&width=32",
        text: "same strategy lmao let's go",
        likes: 120,
        liked: false,
        timestamp: "14h",
        replyingTo: "Aesthetic Arc",
      },
    ],
  },
  {
    id: "7",
    name: "Daily Dose Hype",
    avatar: "/placeholder.svg?height=44&width=44",
    text: "The way this went viral literally overnight is insane. Deserved!",
    likes: 1023,
    liked: false,
    timestamp: "10h",
    replies: [],
  },
  {
    id: "8",
    name: "Midnight Scroller",
    avatar: "/placeholder.svg?height=44&width=44",
    text: "okay but can we talk about that transition at 0:14??",
    likes: 874,
    liked: false,
    timestamp: "8h",
    replies: [],
  },
  {
    id: "9",
    name: "Coffee Shop Vibes",
    avatar: "/placeholder.svg?height=44&width=44",
    text: "showing this to everyone i know. this is a masterpiece.",
    likes: 567,
    liked: false,
    timestamp: "5h",
    replies: [],
  },
  {
    id: "10",
    name: "Lurker No More",
    avatar: "/placeholder.svg?height=44&width=44",
    text: "i never comment but i HAD to for this one",
    likes: 320,
    liked: false,
    timestamp: "3h",
    replies: [],
  },
];
